# Generated by Django 5.0.6 on 2024-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpenses',
            name='created_by',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
